---
title: "Effect of Population Density on Life Expectancy"
author: "Maria Benavides"
date: "`r lubridate::today()`"
output: github_document
---

```{r setup}
library(tidyverse)
library(geonames)
library(countrycode)
library(here)
library(kableExtra)

key <- getOption("geonamesUsername") # Call geonames username to access data
theme_set(new = theme_minimal())
```

```{r import & merge data}
# Import data 
gapminder_df <- gapminder::gapminder
geonames_df <- GNcountryInfo() %>%
  rename(
    country = countryCode
  )

# Create key to join
gapminder_key <- gapminder_df %>%
  mutate(
    country = countrycode(
      country, 
      origin = "country.name", 
      destination = "iso2c"
    )
  )

# Merge dataframes based on the country variable
all_variables <- left_join(
  gapminder_key, geonames_df, by = "country"
  ) %>%
  select( # Select only variables of interest for this exercise
   country,
   lifeExp,
   pop,
   areaInSqKm, 
   year
  ) %>%
  mutate(
    areaInSqKm = as.numeric(areaInSqKm))

```

```{r correlation lifeExp & pop density}
# Add new variable for pop density 
all_variables <- all_variables %>%
  mutate(
    pop_density = pop / areaInSqKm
  )


```


## Session info

```{r, echo = TRUE}
devtools::session_info()
```
